<?php namespace Application\Missions\Gold\Api;

use Application\Entity\Event;
use Application\Entity\Submission;
use Atomino\Gold\Gold;
use Atomino\Gold\GoldApi;
use Atomino\Carbon\Database\Finder\Filter;
use Atomino\Carbon\Entity;

#[Gold(Submission::class, 5, true)]
class SubmissionApi extends GoldApi {
	protected function listExport(Entity $item): array {
		/** @var Submission $item */
		$data = parent::listExport($item); // TODO: Change the autogenerated stub
		$data['userName'] = $item->user->name;
		return $data;
	}
}
