<?php namespace Application\Missions\Gold\Api;

use Application\Entity\Event;
use Application\Entity\Submission;
use Atomino\Gold\Gold;
use Atomino\Gold\GoldApi;
use Atomino\Carbon\Database\Finder\Filter;
use Atomino\Carbon\Entity;
use Atomino\Gold\GoldSorting;
use Atomino\Gold\GoldView;

#[Gold(Submission::class, 50, true)]
class SubmissionApi extends GoldApi {
	protected function listExport(Entity $item): array {
		/** @var Submission $item */
		$data = parent::listExport($item); // TODO: Change the autogenerated stub
		$data['userName'] = $item->user->name;
		return $data;
	}

	public function addViews(): void {
		parent::addViews();
		$this->addView(new GoldView('all', 'all', fn() => null));
		$this->addView(new GoldView('accepted', 'accepted', fn() => Filter::where(Submission::status(Submission::status__accepted))));
		$this->addView(new GoldView('under-review', 'under review', fn() => Filter::where(Submission::status(Submission::status__underReview))));
	}

	public function addSortings(): void {
		parent::addSortings();
		$this->addSorting(new GoldSorting('title', 'title', fn(bool $asc)=> $asc ? [[Submission::title(), "asc"]] : [[Submission::title(), "desc"]]));
	}

}
